/**
 * Common symptom suggestions for the autocomplete input.
 * Keep this list sorted alphabetically for binary-search friendly usage.
 */
export const SYMPTOM_SUGGESTIONS: string[] = [
  'Abdominal pain',
  'Acid reflux',
  'Back pain',
  'Blurred vision',
  'Body ache',
  'Breathlessness',
  'Burning urination',
  'Chest pain',
  'Chills',
  'Cold sweats',
  'Constipation',
  'Cough',
  'Diarrhea',
  'Dizziness',
  'Dry mouth',
  'Ear pain',
  'Excessive thirst',
  'Eye redness',
  'Fatigue',
  'Fever',
  'Frequent urination',
  'Headache',
  'Heartburn',
  'High blood pressure',
  'Insomnia',
  'Itching',
  'Joint pain',
  'Loss of appetite',
  'Loss of taste',
  'Low blood pressure',
  'Memory loss',
  'Migraine',
  'Muscle cramps',
  'Muscle weakness',
  'Nausea',
  'Neck stiffness',
  'Night sweats',
  'Numbness',
  'Palpitations',
  'Rash',
  'Runny nose',
  'Shortness of breath',
  'Skin discoloration',
  'Sneezing',
  'Sore throat',
  'Stomach cramps',
  'Swelling',
  'Tingling sensation',
  'Tremors',
  'Vomiting',
  'Weight gain',
  'Weight loss',
  'Wheezing',
];
