"""
Medical Agent Orchestrator
───────────────────────────
Receives the predicted disease from the NN model and dispatches it
to all 4 AI agents concurrently using ThreadPoolExecutor.
Returns a unified, structured response.
"""

import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Dict, Any

from .recommendation_agent import RecommendationAgent
from .treatment_agent import TreatmentExplorationAgent
from .clinical_guidelines_agent import ClinicalGuidelinesAgent
from .lifestyle_diet_agent import LifestyleDietAgent


class MedicalAgentOrchestrator:
    """
    Orchestrates the 4 medical AI agents:
      1. Recommendation Agent         (Gemma 3 27B)
      2. Treatment Exploration Agent   (GPT-4.1-nano)
      3. Clinical Guidelines Agent     (Llama 4 Maverick)
      4. Lifestyle & Diet Agent        (Microsoft Phi-4)

    All agents run in parallel for maximum speed.
    """

    GLOBAL_DISCLAIMER = (
        "🚨 IMPORTANT MEDICAL NOTICE: All information below is generated by AI agents "
        "using different large language models. This content is strictly for informational "
        "and educational purposes. It does NOT replace professional medical advice, diagnosis, "
        "or treatment. If you are experiencing a medical emergency, call your local emergency "
        "services immediately. Always consult with a qualified healthcare professional for any "
        "health concerns or before making changes to your treatment plan."
    )

    def __init__(self):
        # Lazy initialization — agents are created on first use
        self._agents_initialized = False
        self._agents = {}

    def _initialize_agents(self):
        """Initialize all 4 agents (called once on first request)."""
        if self._agents_initialized:
            return

        self._agents = {
            "recommendation": RecommendationAgent(),
            "treatment_exploration": TreatmentExplorationAgent(),
            "clinical_guidelines": ClinicalGuidelinesAgent(),
            "lifestyle_and_diet": LifestyleDietAgent(),
        }
        self._agents_initialized = True

    def run(self, disease: str, symptoms: str = "") -> Dict[str, Any]:
        """
        Execute all 4 agents in parallel using ThreadPoolExecutor.
        Each agent runs on its own thread to maximize throughput and utilizes
        its own unique API key and model as configured in the .env file.

        Args:
            disease:  The disease name predicted by the NN model.
            symptoms: Raw symptom text from the patient (optional).

        Returns:
            Structured dictionary with results from all agents plus metadata.
        """
        self._initialize_agents()
        start_time = time.time()

        results = {}
        errors = {}

        # Map internal keys to agent instances
        agent_tasks = {
            "recommendation": self._agents.get("recommendation"),
            "treatment_exploration": self._agents.get("treatment_exploration"),
            "clinical_guidelines": self._agents.get("clinical_guidelines"),
            "lifestyle_and_diet": self._agents.get("lifestyle_and_diet"),
        }

        print(f"DEBUG: Starting 4 agents in parallel for disease: {disease}")

        with ThreadPoolExecutor(max_workers=4) as executor:
            # Submit all agent tasks
            future_to_name = {
                executor.submit(agent.run, disease, symptoms): name
                for name, agent in agent_tasks.items() if agent
            }

            # Process results as they complete
            for future in as_completed(future_to_name):
                name = future_to_name[future]
                try:
                    data = future.result()
                    results[name] = data
                except Exception as e:
                    print(f"DEBUG: Agent [{name}] FAILED concurrently: {str(e)}")
                    agent_instance = agent_tasks.get(name)
                    errors[name] = {
                        "error": str(e),
                        "agent_name": name,
                        "medical_disclaimer": getattr(agent_instance, 'DISCLAIMER', self.GLOBAL_DISCLAIMER),
                    }

        elapsed = round(time.time() - start_time, 2)
        print(f"DEBUG: Parallel execution completed in {elapsed}s")

        # Build unified response
        response = {
            "status": "completed" if not errors else ("partial" if results else "failed"),
            "predicted_disease": disease,
            "symptoms_analyzed": symptoms,
            "processing_time_seconds": elapsed,
            "global_medical_disclaimer": self.GLOBAL_DISCLAIMER,
            "agents": {
                "recommendation": results.get("recommendation", errors.get("recommendation", {})),
                "treatment_exploration": results.get("treatment_exploration", errors.get("treatment_exploration", {})),
                "clinical_guidelines": results.get("clinical_guidelines", errors.get("clinical_guidelines", {})),
                "lifestyle_and_diet": results.get("lifestyle_and_diet", errors.get("lifestyle_and_diet", {})),
            },
        }

        if errors:
            response["errors"] = errors

        return response


# Singleton instance
medical_orchestrator = MedicalAgentOrchestrator()
